package com.project.mynoize.util

val genres = listOf(
    "R&B / Soul",
    "Jazz",
    "Blues",
    "Classical",
    "Country",
    "Electronic",
    "Folk / World",
    "Hip Hop / Rap",
    "Latin",
    "Pop",
    "Reggae",
    "Rock",
)

val subGenreMap: HashMap<String, List<String>> = hashMapOf(
    "R&B / Soul" to SubGenres.RB_SoulList,
    "Jazz" to SubGenres.Jazz,
    "Blues" to SubGenres.Blues,
    "Classical" to SubGenres.Classical,
    "Country" to SubGenres.Country,
    "Electronic" to SubGenres.Electronic,
    "Folk / World" to SubGenres.Folk,
    "Hip Hop / Rap" to SubGenres.HipHopRap,
    "Latin" to SubGenres.latinGenres,
    "Pop" to SubGenres.popGenres,
    "Reggae" to SubGenres.reggaeGenres,
    "Rock" to SubGenres.rockGenres,

)

object SubGenres{
    val RB_SoulList : List<String> = listOf(
        "Boogie",
        "Disco",
        "Doo Wop",
        "Funk",
        "Go Go",
        "Gospel",
        "Indie Soul",
        "Neo-Soul",
        "New Jack Swing",
        "P-Funk",
        "Psychedelic Funk",
        "Psychedelic Soul",
        "R&B (Contemporary)",
        "Rhythm & Blues",
        "Soul",
        "Synth Funk"
    )

    val Jazz = listOf(
        "Afro Cuban",
        "Avant-Garde / Free Jazz",
        "Bebop",
        "Big Band",
        "Contemporary Jazz",
        "Dixieland",
        "Jazz-Funk",
        "Jazz Fusion",
        "Jazz Manouche",
        "Latin Jazz",
        "Modal Jazz",
        "Nu Jazz / Acid Jazz",
        "Post Bop",
        "Ragtime",
        "Senegalese Jazz",
        "Smooth Jazz",
        "Soul Jazz",
        "Swing"
    )

    val Blues = listOf(
        "Boogie-Woogie",
        "Chicago Blues",
        "Country Blues",
        "Delta Blues",
        "Electric Blues"
    )

    val Classical = listOf(
        "Ballet Music",
        "Beijing Opera",
        "Cantonese Opera",
        "Huangmei Opera",
        "March",
        "Modern Classical",
        "Opera",
        "Revolutionary Beijing Opera",
        "Shanghai Opera",
        "Shaoxing Opera",
        "Song Poetry",
        "Waltz"
    )

    val Country = listOf(
        "Americana",
        "Bluegrass",
        "Country Gospel",
        "Honky Tonk",
        "Western"
    )

    val Electronic = listOf(
        "Afrobeats",
        "Amapiano",
        "Ambient",
        "Balearic",
        "Breakbeat",
        "Dance",
        "Detroit Techno",
        "Downtempo / Electronica",
        "Drone",
        "Drum'n'Bass / Jungle",
        "Dubstep",
        "Electro",
        "Euro Dance",
        "Experimental",
        "Freestyle",
        "House",
        "Indie Dance / Nu Disco",
        "Kuduro",
        "Kwaito",
        "Lo-Fi Beats",
        "Miami Bass",
        "Moombahton",
        "Noise / Industrial",
        "Reggaeton",
        "Synth Pop",
        "Synthwave",
        "Tech House",
        "Techno",
        "Trance",
        "Trip Hop",
        "UK Garage / 2-step"
    )

    val Folk = listOf(
        "African",
        "Afrobeat",
        "Afro Manding",
        "Afro Pop",
        "Algerian",
        "Apala",
        "Arabic",
        "Arabic Folk",
        "Asian",
        "Balinese",
        "Bambara",
        "Bhajan",
        "Bhangra",
        "Bolivian",
        "Bulgarian",
        "Cajun / Zydeco",
        "Calypso",
        "Cameroon",
        "Caribbean",
        "Carnatic",
        "Chinese",
        "Chinese Folk",
        "Chinese Lite Music",
        "Chinese Neo-Folk",
        "Chinese Revolutionary",
        "Congolese",
        "English Folk",
        "Ethiopian",
        "Flamenco",
        "Folk",
        "Franco-Arabic",
        "Fuji",
        "Funaná",
        "Geet",
        "Ghazal",
        "Global Grooves",
        "Guinea",
        "Haitian",
        "Hawaiian",
        "Highlife",
        "Hindustani",
        "Hungarian",
        "Indian",
        "Indian Classical",
        "Indian Spiritual / Devotional",
        "Indie Folk",
        "Indonesian",
        "Inuit",
        "Iranian",
        "Iraqi",
        "Italian",
        "Japanese",
        "Javanese",
        "Jùjú",
        "Koladera",
        "Korean",
        "Lao",
        "Madagascar",
        "Malagasy",
        "Mali",
        "Mazurka",
        "Mbalax",
        "Mediterranean",
        "Middle Eastern",
        "Mongolian",
        "Moroccan",
        "Mozambican",
        "Nigerian",
        "Palestinian",
        "Paraguayan",
        "Persian",
        "Peruvian",
        "Polka",
        "Punjabi",
        "Qawwali",
        "Raga",
        "Scottish",
        "Semba",
        "Senegalese",
        "Serbian",
        "Singer-Songwriter",
        "Spanish",
        "Sufi",
        "Swedish",
        "Taiwanese",
        "Tanzanian",
        "Tarantella",
        "Thai",
        "Tibetan",
        "Traditional Folk",
        "Turkish",
        "Vietnamese",
        "Vocal",
        "West African"
    )

    val HipHopRap = listOf(
        "Alternative Rap",
        "Beats",
        "Gangsta Rap",
        "Grime",
        "Hip Hop",
        "Latin Rap",
        "Old School Rap",
        "Rap",
        "Trap"
    )

    val latinGenres = listOf(
        "Afro Latin",
        "Arrocha",
        "Bachata",
        "Baião",
        "Bolero",
        "Bolero Son",
        "Boogaloo",
        "Bossa Nova",
        "Brazilian",
        "Charanga",
        "Choro",
        "Coco",
        "Colombian",
        "Cuban",
        "Cumbia",
        "Forró",
        "Frevo",
        "Funk Carioca / Baile Funk",
        "Guaguanco",
        "Guaracha",
        "Guaracha Jibara",
        "Guarani",
        "Mambo",
        "Mangue Beat",
        "Maracatu",
        "Merengue",
        "Mexican",
        "Milonga",
        "MPB",
        "Pagode",
        "Puerto Rican",
        "Ranchera",
        "Rumba",
        "Salsa Cha",
        "Salsa y Tropical",
        "Samba",
        "Son",
        "Songo",
        "Son Montuno",
        "Son Tumbao",
        "Tamborito",
        "Tango",
        "Timba",
        "Urban Latino",
        "Vals",
        "Zouk"
    )

    val popGenres = listOf(
        "Pop",
        "K-Pop",
        "Adult Contemporary",
        "Alternative / Indie Pop",
        "Ballad",
        "Chinese Pop",
        "Chinese Pop / Rock",
        "Indian Pop",
        "Psychedelic Pop",
        "Sunshine Pop"
    )

    val reggaeGenres = listOf(
        "Dancehall",
        "Dub",
        "Ska / Rocksteady")

    val rockGenres = listOf(
        "Alternative / Indie Rock",
        "Blues Rock",
        "Folk Rock",
        "Garage Rock",
        "Hard Rock / Heavy Metal",
        "Kraut Rock / Kosmische",
        "Metal",
        "New Wave / Post Punk",
        "Post-Rock",
        "Prog Rock",
        "Psychedelic Rock",
        "Punk",
        "Soft Rock",
        "Surf Rock"
    )

}
