package com.project.mynoize.util

enum class Country(val displayName: String) {
    // EU Countries (27)
    CROATIA("Croatia"),
    SERBIA("Serbia"),
    BOSNIA_AND_HERZEGOVINA("Bosnia and Herzegovina"),
    UNITED_KINGDOM("United Kingdom"),
    UNITED_STATES("United States"),
    ITALY("Italy"),
    MACEDONIA("Macedonia"),
    SOUTH_KOREA("South Korea"),
    JAPAN("Japan"),
    AUSTRIA("Austria"),
    BELGIUM("Belgium"),
    BULGARIA("Bulgaria"),
    CYPRUS("Cyprus"),
    CZECH_REPUBLIC("Czech Republic"),
    DENMARK("Denmark"),
    ESTONIA("Estonia"),
    FINLAND("Finland"),
    FRANCE("France"),
    GERMANY("Germany"),
    GREECE("Greece"),
    HUNGARY("Hungary"),
    IRELAND("Ireland"),
    LATVIA("Latvia"),
    LITHUANIA("Lithuania"),
    LUXEMBOURG("Luxembourg"),
    MALTA("Malta"),
    NETHERLANDS("Netherlands"),
    POLAND("Poland"),
    PORTUGAL("Portugal"),
    ROMANIA("Romania"),
    SLOVAKIA("Slovakia"),
    SLOVENIA("Slovenia"),
    SPAIN("Spain"),
    SWEDEN("Sweden"),
    CHINA("China"),
    INDIA("India"),
    BRAZIL("Brazil"),
    RUSSIA("Russia"),
    CANADA("Canada"),
    AUSTRALIA("Australia"),
    OTHER("Other");

    companion object {
        fun fromDisplayName(name: String): Country? =
            entries.find { it.displayName == name }
    }
}

enum class Mood(val displayName: String) {
    MELANCHOLIC("melancholic"),
    ATMOSPHERIC("atmospheric"),
    HAPPY("happy"),
    SAD("sad"),
    ENERGETIC("energetic"),
    CALM("calm"),
    ROMANTIC("romantic"),
    AGGRESSIVE("aggressive"),
    NOSTALGIC("nostalgic"),
    DREAMY("dreamy"),
    DARK("dark"),
    UPLIFTING("uplifting"),
    MYSTERIOUS("mysterious"),
    PLAYFUL("playful"),
    TENSE("tense");

    companion object {
        fun fromDisplayName(name: String): Mood? =
            entries.find { it.displayName == name }
    }
}

enum class Language(val displayName: String) {
    ENGLISH("en"),
    CROATIAN("hr"),
    SERBIAN("rs"),
    BOSNIAN("ba"),
    ITALIAN("it"),
    JAPANESE("ja"),
    SPANISH("es"),
    FRENCH("fr"),
    GERMAN("de"),
    PORTUGUESE("pt"),
    KOREAN("ko"),
    CHINESE("cn"),
    ARABIC("ar"),
    RUSSIAN("ru"),
    HINDI("hi"),
    DUTCH("nl"),
    SWEDISH("sv"),
    POLISH("pl"),
    TURKISH("tr"),
    DANISH("da"),
    NORWEGIAN("no"),
    FINNISH("fi");

    companion object {
        fun fromDisplayName(name: String): Language? =
            entries.find { it.displayName == name }
    }
}

enum class Era(val displayName: String) {
    TWENTIES_MODERN("20s-modern"),
    TENS("10s"),
    TWO_THOUSANDS("2000s"),
    NINETIES("90s"),
    EIGHTIES("80s"),
    SEVENTIES("70s"),
    SIXTIES("60s"),
    FIFTIES("50s"),
    FORTIES("40s"),
    THIRTIES("30s"),
    TWENTIES("20s");

    companion object {
        fun fromDisplayName(name: String): Era? =
            entries.find { it.displayName == name }
    }
}


enum class Genre(val displayName: String) {
    RNB_SOUL("R&B / Soul"),
    JAZZ("Jazz"),
    BLUES("Blues"),
    CLASSICAL("Classical"),
    COUNTRY("Country"),
    ELECTRONIC("Electronic"),
    FOLK_WORLD("Folk / World"),
    HIP_HOP_RAP("Hip Hop / Rap"),
    LATIN("Latin"),
    POP("Pop"),
    REGGAE("Reggae"),
    ROCK("Rock");

    companion object {
        fun fromDisplayName(name: String): Genre? =
            entries.find { it.displayName == name }
    }
}
enum class SubGenre(val displayName: String, val genre: Genre) {

    // R&B / Soul
    BOOGIE("Boogie", Genre.RNB_SOUL),
    DISCO("Disco", Genre.RNB_SOUL),
    DOO_WOP("Doo Wop", Genre.RNB_SOUL),
    FUNK("Funk", Genre.RNB_SOUL),
    GO_GO("Go Go", Genre.RNB_SOUL),
    GOSPEL("Gospel", Genre.RNB_SOUL),
    INDIE_SOUL("Indie Soul", Genre.RNB_SOUL),
    NEO_SOUL("Neo-Soul", Genre.RNB_SOUL),
    NEW_JACK_SWING("New Jack Swing", Genre.RNB_SOUL),
    P_FUNK("P-Funk", Genre.RNB_SOUL),
    PSYCHEDELIC_FUNK("Psychedelic Funk", Genre.RNB_SOUL),
    PSYCHEDELIC_SOUL("Psychedelic Soul", Genre.RNB_SOUL),
    RNB_CONTEMPORARY("R&B (Contemporary)", Genre.RNB_SOUL),
    RHYTHM_AND_BLUES("Rhythm & Blues", Genre.RNB_SOUL),
    SOUL("Soul", Genre.RNB_SOUL),
    SYNTH_FUNK("Synth Funk", Genre.RNB_SOUL),

    // Jazz
    AFRO_CUBAN("Afro Cuban", Genre.JAZZ),
    AVANT_GARDE_FREE_JAZZ("Avant-Garde / Free Jazz", Genre.JAZZ),
    BEBOP("Bebop", Genre.JAZZ),
    BIG_BAND("Big Band", Genre.JAZZ),
    CONTEMPORARY_JAZZ("Contemporary Jazz", Genre.JAZZ),
    DIXIELAND("Dixieland", Genre.JAZZ),
    JAZZ_FUNK("Jazz-Funk", Genre.JAZZ),
    JAZZ_FUSION("Jazz Fusion", Genre.JAZZ),
    JAZZ_MANOUCHE("Jazz Manouche", Genre.JAZZ),
    LATIN_JAZZ("Latin Jazz", Genre.JAZZ),
    MODAL_JAZZ("Modal Jazz", Genre.JAZZ),
    NU_JAZZ_ACID_JAZZ("Nu Jazz / Acid Jazz", Genre.JAZZ),
    POST_BOP("Post Bop", Genre.JAZZ),
    RAGTIME("Ragtime", Genre.JAZZ),
    SENEGALESE_JAZZ("Senegalese Jazz", Genre.JAZZ),
    SMOOTH_JAZZ("Smooth Jazz", Genre.JAZZ),
    SOUL_JAZZ("Soul Jazz", Genre.JAZZ),
    SWING("Swing", Genre.JAZZ),

    // Blues
    BOOGIE_WOOGIE("Boogie-Woogie", Genre.BLUES),
    CHICAGO_BLUES("Chicago Blues", Genre.BLUES),
    COUNTRY_BLUES("Country Blues", Genre.BLUES),
    DELTA_BLUES("Delta Blues", Genre.BLUES),
    ELECTRIC_BLUES("Electric Blues", Genre.BLUES),

    // Classical
    BALLET_MUSIC("Ballet Music", Genre.CLASSICAL),
    BEIJING_OPERA("Beijing Opera", Genre.CLASSICAL),
    CANTONESE_OPERA("Cantonese Opera", Genre.CLASSICAL),
    HUANGMEI_OPERA("Huangmei Opera", Genre.CLASSICAL),
    MARCH("March", Genre.CLASSICAL),
    MODERN_CLASSICAL("Modern Classical", Genre.CLASSICAL),
    OPERA("Opera", Genre.CLASSICAL),
    REVOLUTIONARY_BEIJING_OPERA("Revolutionary Beijing Opera", Genre.CLASSICAL),
    SHANGHAI_OPERA("Shanghai Opera", Genre.CLASSICAL),
    SHAOXING_OPERA("Shaoxing Opera", Genre.CLASSICAL),
    SONG_POETRY("Song Poetry", Genre.CLASSICAL),
    WALTZ("Waltz", Genre.CLASSICAL),

    // Country
    AMERICANA("Americana", Genre.COUNTRY),
    BLUEGRASS("Bluegrass", Genre.COUNTRY),
    COUNTRY_GOSPEL("Country Gospel", Genre.COUNTRY),
    HONKY_TONK("Honky Tonk", Genre.COUNTRY),
    WESTERN("Western", Genre.COUNTRY),

    // Electronic
    AFROBEATS("Afrobeats", Genre.ELECTRONIC),
    AMAPIANO("Amapiano", Genre.ELECTRONIC),
    AMBIENT("Ambient", Genre.ELECTRONIC),
    BALEARIC("Balearic", Genre.ELECTRONIC),
    BREAKBEAT("Breakbeat", Genre.ELECTRONIC),
    DANCE("Dance", Genre.ELECTRONIC),
    DETROIT_TECHNO("Detroit Techno", Genre.ELECTRONIC),
    DOWNTEMPO_ELECTRONICA("Downtempo / Electronica", Genre.ELECTRONIC),
    DRONE("Drone", Genre.ELECTRONIC),
    DRUM_N_BASS_JUNGLE("Drum'n'Bass / Jungle", Genre.ELECTRONIC),
    DUBSTEP("Dubstep", Genre.ELECTRONIC),
    ELECTRO("Electro", Genre.ELECTRONIC),
    EURO_DANCE("Euro Dance", Genre.ELECTRONIC),
    EXPERIMENTAL("Experimental", Genre.ELECTRONIC),
    FREESTYLE("Freestyle", Genre.ELECTRONIC),
    HOUSE("House", Genre.ELECTRONIC),
    INDIE_DANCE_NU_DISCO("Indie Dance / Nu Disco", Genre.ELECTRONIC),
    KUDURO("Kuduro", Genre.ELECTRONIC),
    KWAITO("Kwaito", Genre.ELECTRONIC),
    LO_FI_BEATS("Lo-Fi Beats", Genre.ELECTRONIC),
    MIAMI_BASS("Miami Bass", Genre.ELECTRONIC),
    MOOMBAHTON("Moombahton", Genre.ELECTRONIC),
    NOISE_INDUSTRIAL("Noise / Industrial", Genre.ELECTRONIC),
    REGGAETON("Reggaeton", Genre.ELECTRONIC),
    SYNTH_POP("Synth Pop", Genre.ELECTRONIC),
    SYNTHWAVE("Synthwave", Genre.ELECTRONIC),
    TECH_HOUSE("Tech House", Genre.ELECTRONIC),
    TECHNO("Techno", Genre.ELECTRONIC),
    TRANCE("Trance", Genre.ELECTRONIC),
    TRIP_HOP("Trip Hop", Genre.ELECTRONIC),
    UK_GARAGE_2STEP("UK Garage / 2-step", Genre.ELECTRONIC),

    // Folk / World
    AFRICAN("African", Genre.FOLK_WORLD),
    AFROBEAT("Afrobeat", Genre.FOLK_WORLD),
    AFRO_MANDING("Afro Manding", Genre.FOLK_WORLD),
    AFRO_POP("Afro Pop", Genre.FOLK_WORLD),
    ALGERIAN("Algerian", Genre.FOLK_WORLD),
    APALA("Apala", Genre.FOLK_WORLD),
    ARABIC("Arabic", Genre.FOLK_WORLD),
    ARABIC_FOLK("Arabic Folk", Genre.FOLK_WORLD),
    ASIAN("Asian", Genre.FOLK_WORLD),
    BALINESE("Balinese", Genre.FOLK_WORLD),
    BAMBARA("Bambara", Genre.FOLK_WORLD),
    BHAJAN("Bhajan", Genre.FOLK_WORLD),
    BHANGRA("Bhangra", Genre.FOLK_WORLD),
    BOLIVIAN("Bolivian", Genre.FOLK_WORLD),
    BULGARIAN("Bulgarian", Genre.FOLK_WORLD),
    CAJUN_ZYDECO("Cajun / Zydeco", Genre.FOLK_WORLD),
    CALYPSO("Calypso", Genre.FOLK_WORLD),
    CAMEROON("Cameroon", Genre.FOLK_WORLD),
    CARIBBEAN("Caribbean", Genre.FOLK_WORLD),
    CARNATIC("Carnatic", Genre.FOLK_WORLD),
    CHINESE("Chinese", Genre.FOLK_WORLD),
    CHINESE_FOLK("Chinese Folk", Genre.FOLK_WORLD),
    CHINESE_LITE_MUSIC("Chinese Lite Music", Genre.FOLK_WORLD),
    CHINESE_NEO_FOLK("Chinese Neo-Folk", Genre.FOLK_WORLD),
    CHINESE_REVOLUTIONARY("Chinese Revolutionary", Genre.FOLK_WORLD),
    CONGOLESE("Congolese", Genre.FOLK_WORLD),
    ENGLISH_FOLK("English Folk", Genre.FOLK_WORLD),
    ETHIOPIAN("Ethiopian", Genre.FOLK_WORLD),
    FLAMENCO("Flamenco", Genre.FOLK_WORLD),
    FOLK("Folk", Genre.FOLK_WORLD),
    FRANCO_ARABIC("Franco-Arabic", Genre.FOLK_WORLD),
    FUJI("Fuji", Genre.FOLK_WORLD),
    FUNANA("Funaná", Genre.FOLK_WORLD),
    GEET("Geet", Genre.FOLK_WORLD),
    GHAZAL("Ghazal", Genre.FOLK_WORLD),
    GLOBAL_GROOVES("Global Grooves", Genre.FOLK_WORLD),
    GUINEA("Guinea", Genre.FOLK_WORLD),
    HAITIAN("Haitian", Genre.FOLK_WORLD),
    HAWAIIAN("Hawaiian", Genre.FOLK_WORLD),
    HIGHLIFE("Highlife", Genre.FOLK_WORLD),
    HINDUSTANI("Hindustani", Genre.FOLK_WORLD),
    HUNGARIAN("Hungarian", Genre.FOLK_WORLD),
    INDIAN("Indian", Genre.FOLK_WORLD),
    INDIAN_CLASSICAL("Indian Classical", Genre.FOLK_WORLD),
    INDIAN_SPIRITUAL_DEVOTIONAL("Indian Spiritual / Devotional", Genre.FOLK_WORLD),
    INDIE_FOLK("Indie Folk", Genre.FOLK_WORLD),
    INDONESIAN("Indonesian", Genre.FOLK_WORLD),
    INUIT("Inuit", Genre.FOLK_WORLD),
    IRANIAN("Iranian", Genre.FOLK_WORLD),
    IRAQI("Iraqi", Genre.FOLK_WORLD),
    ITALIAN("Italian", Genre.FOLK_WORLD),
    JAPANESE("Japanese", Genre.FOLK_WORLD),
    JAVANESE("Javanese", Genre.FOLK_WORLD),
    JUJU("Jùjú", Genre.FOLK_WORLD),
    KOLADERA("Koladera", Genre.FOLK_WORLD),
    KOREAN("Korean", Genre.FOLK_WORLD),
    LAO("Lao", Genre.FOLK_WORLD),
    MADAGASCAR("Madagascar", Genre.FOLK_WORLD),
    MALAGASY("Malagasy", Genre.FOLK_WORLD),
    MALI("Mali", Genre.FOLK_WORLD),
    MAZURKA("Mazurka", Genre.FOLK_WORLD),
    MBALAX("Mbalax", Genre.FOLK_WORLD),
    MEDITERRANEAN("Mediterranean", Genre.FOLK_WORLD),
    MIDDLE_EASTERN("Middle Eastern", Genre.FOLK_WORLD),
    MONGOLIAN("Mongolian", Genre.FOLK_WORLD),
    MOROCCAN("Moroccan", Genre.FOLK_WORLD),
    MOZAMBICAN("Mozambican", Genre.FOLK_WORLD),
    NIGERIAN("Nigerian", Genre.FOLK_WORLD),
    PALESTINIAN("Palestinian", Genre.FOLK_WORLD),
    PARAGUAYAN("Paraguayan", Genre.FOLK_WORLD),
    PERSIAN("Persian", Genre.FOLK_WORLD),
    PERUVIAN("Peruvian", Genre.FOLK_WORLD),
    POLKA("Polka", Genre.FOLK_WORLD),
    PUNJABI("Punjabi", Genre.FOLK_WORLD),
    QAWWALI("Qawwali", Genre.FOLK_WORLD),
    RAGA("Raga", Genre.FOLK_WORLD),
    SCOTTISH("Scottish", Genre.FOLK_WORLD),
    SEMBA("Semba", Genre.FOLK_WORLD),
    SENEGALESE("Senegalese", Genre.FOLK_WORLD),
    SERBIAN("Serbian", Genre.FOLK_WORLD),
    SINGER_SONGWRITER("Singer-Songwriter", Genre.FOLK_WORLD),
    SPANISH("Spanish", Genre.FOLK_WORLD),
    SUFI("Sufi", Genre.FOLK_WORLD),
    SWEDISH("Swedish", Genre.FOLK_WORLD),
    TAIWANESE("Taiwanese", Genre.FOLK_WORLD),
    TANZANIAN("Tanzanian", Genre.FOLK_WORLD),
    TARANTELLA("Tarantella", Genre.FOLK_WORLD),
    THAI("Thai", Genre.FOLK_WORLD),
    TIBETAN("Tibetan", Genre.FOLK_WORLD),
    TRADITIONAL_FOLK("Traditional Folk", Genre.FOLK_WORLD),
    TURKISH("Turkish", Genre.FOLK_WORLD),
    VIETNAMESE("Vietnamese", Genre.FOLK_WORLD),
    VOCAL("Vocal", Genre.FOLK_WORLD),
    WEST_AFRICAN("West African", Genre.FOLK_WORLD),

    // Hip Hop / Rap
    ALTERNATIVE_RAP("Alternative Rap", Genre.HIP_HOP_RAP),
    BEATS("Beats", Genre.HIP_HOP_RAP),
    GANGSTA_RAP("Gangsta Rap", Genre.HIP_HOP_RAP),
    GRIME("Grime", Genre.HIP_HOP_RAP),
    HIP_HOP("Hip Hop", Genre.HIP_HOP_RAP),
    LATIN_RAP("Latin Rap", Genre.HIP_HOP_RAP),
    OLD_SCHOOL_RAP("Old School Rap", Genre.HIP_HOP_RAP),
    RAP("Rap", Genre.HIP_HOP_RAP),
    TRAP("Trap", Genre.HIP_HOP_RAP),

    // Latin
    AFRO_LATIN("Afro Latin", Genre.LATIN),
    ARROCHA("Arrocha", Genre.LATIN),
    BACHATA("Bachata", Genre.LATIN),
    BAIAO("Baião", Genre.LATIN),
    BOLERO("Bolero", Genre.LATIN),
    BOLERO_SON("Bolero Son", Genre.LATIN),
    BOOGALOO("Boogaloo", Genre.LATIN),
    BOSSA_NOVA("Bossa Nova", Genre.LATIN),
    BRAZILIAN("Brazilian", Genre.LATIN),
    CHARANGA("Charanga", Genre.LATIN),
    CHORO("Choro", Genre.LATIN),
    COCO("Coco", Genre.LATIN),
    COLOMBIAN("Colombian", Genre.LATIN),
    CUBAN("Cuban", Genre.LATIN),
    CUMBIA("Cumbia", Genre.LATIN),
    FORRO("Forró", Genre.LATIN),
    FREVO("Frevo", Genre.LATIN),
    FUNK_CARIOCA_BAILE_FUNK("Funk Carioca / Baile Funk", Genre.LATIN),
    GUAGUANCO("Guaguanco", Genre.LATIN),
    GUARACHA("Guaracha", Genre.LATIN),
    GUARACHA_JIBARA("Guaracha Jibara", Genre.LATIN),
    GUARANI("Guarani", Genre.LATIN),
    MAMBO("Mambo", Genre.LATIN),
    MANGUE_BEAT("Mangue Beat", Genre.LATIN),
    MARACATU("Maracatu", Genre.LATIN),
    MERENGUE("Merengue", Genre.LATIN),
    MEXICAN("Mexican", Genre.LATIN),
    MILONGA("Milonga", Genre.LATIN),
    MPB("MPB", Genre.LATIN),
    PAGODE("Pagode", Genre.LATIN),
    PUERTO_RICAN("Puerto Rican", Genre.LATIN),
    RANCHERA("Ranchera", Genre.LATIN),
    RUMBA("Rumba", Genre.LATIN),
    SALSA_CHA("Salsa Cha", Genre.LATIN),
    SALSA_Y_TROPICAL("Salsa y Tropical", Genre.LATIN),
    SAMBA("Samba", Genre.LATIN),
    SON("Son", Genre.LATIN),
    SONGO("Songo", Genre.LATIN),
    SON_MONTUNO("Son Montuno", Genre.LATIN),
    SON_TUMBAO("Son Tumbao", Genre.LATIN),
    TAMBORITO("Tamborito", Genre.LATIN),
    TANGO("Tango", Genre.LATIN),
    TIMBA("Timba", Genre.LATIN),
    URBAN_LATINO("Urban Latino", Genre.LATIN),
    VALS("Vals", Genre.LATIN),
    ZOUK("Zouk", Genre.LATIN),

    // Pop
    POP("Pop", Genre.POP),
    K_POP("K-Pop", Genre.POP),
    ADULT_CONTEMPORARY("Adult Contemporary", Genre.POP),
    ALTERNATIVE_INDIE_POP("Alternative / Indie Pop", Genre.POP),
    BALLAD("Ballad", Genre.POP),
    CHINESE_POP("Chinese Pop", Genre.POP),
    CHINESE_POP_ROCK("Chinese Pop / Rock", Genre.POP),
    INDIAN_POP("Indian Pop", Genre.POP),
    PSYCHEDELIC_POP("Psychedelic Pop", Genre.POP),
    SUNSHINE_POP("Sunshine Pop", Genre.POP),

    // Reggae
    DANCEHALL("Dancehall", Genre.REGGAE),
    DUB("Dub", Genre.REGGAE),
    SKA_ROCKSTEADY("Ska / Rocksteady", Genre.REGGAE),

    // Rock
    ALTERNATIVE_INDIE_ROCK("Alternative / Indie Rock", Genre.ROCK),
    BLUES_ROCK("Blues Rock", Genre.ROCK),
    FOLK_ROCK("Folk Rock", Genre.ROCK),
    GARAGE_ROCK("Garage Rock", Genre.ROCK),
    HARD_ROCK_HEAVY_METAL("Hard Rock / Heavy Metal", Genre.ROCK),
    KRAUT_ROCK_KOSMISCHE("Kraut Rock / Kosmische", Genre.ROCK),
    METAL("Metal", Genre.ROCK),
    NEW_WAVE_POST_PUNK("New Wave / Post Punk", Genre.ROCK),
    POST_ROCK("Post-Rock", Genre.ROCK),
    PROG_ROCK("Prog Rock", Genre.ROCK),
    PSYCHEDELIC_ROCK("Psychedelic Rock", Genre.ROCK),
    PUNK("Punk", Genre.ROCK),
    SOFT_ROCK("Soft Rock", Genre.ROCK),
    SURF_ROCK("Surf Rock", Genre.ROCK);

    companion object {
        fun forGenre(genre: Genre): List<SubGenre> =
            entries.filter { it.genre == genre }

        fun fromDisplayName(name: String): SubGenre? =
            entries.find { it.displayName == name }
    }
}